WHITE="\[\033[00m\]"
BLACK="\[\033[01;30m\]"
RED="\[\033[0;31m\]"
GREEN="\[\033[0;32m\]"
YELLOW="\[\033[0;33m\]"
BLUE="\[\033[0;34m\]"
PURPLE="\[\033[0;35m\]"
CYAN="\[\033[0;36m\]"

function parse_git_branch {
	    ref=$(git-symbolic-ref HEAD 2> /dev/null) || return
		    echo "("${ref#refs/heads/}")"
}

export TERM="xterm-color"
alias ls="ls -G"
export PS1="$PURPLE\u@\h$WHITE:$BLUE\w $YELLOW\$(parse_git_branch)$WHITE\$ "
